import { Payment,columns } from "./columns";
import { DataTable } from "./data-table";

const getData = async (): Promise<Payment[]> => {
  return [
    {
  id: "728ed521",
  userId: "1001",
  amount: 134,
  status: "pending",
  fullName: "John Doe",
  email: "johndoe@gmail.com",
},
{
  id: "728ed522",
  userId: "1002",
  amount: 124,
  status: "success",
  fullName: "Jane Doe",
  email: "janedoe@gmail.com",
},
{
  id: "728ed523",
  userId: "1003",
  amount: 167,
  status: "success",
  fullName: "Mike Galloway",
  email: "mikegalloway@gmail.com",
},
{
  id: "728ed524",
  userId: "1004",
  amount: 156,
  status: "failed",
  fullName: "Minerva Robinson",
  email: "minerbarobinson@gmail.com",
},
{
  id: "728ed525",
  userId: "1005",
  amount: 145,
  status: "success",
  fullName: "Mable Clayton",
  email: "mableclayton@gmail.com",
},
{
  id: "728ed526",
  userId: "1006",
  amount: 189,
  status: "pending",
  fullName: "Nathan McDaniel",
  email: "nathanmcdaniel@gmail.com",
},
{
  id: "728ed527",
  userId: "1007",
  amount: 178,
  status: "success",
  fullName: "Myrtie Lamb",
  email: "myrtielamb@gmail.com",
},
{
  id: "728ed528",
  userId: "1008",
  amount: 190,
  status: "success",
  fullName: "Leona Bryant",
  email: "leonabryant@gmail.com",
},
{
  id: "728ed529",
  userId: "1009",
  amount: 134,
  status: "failed",
  fullName: "Aaron Willis",
  email: "aaronwillis@gmail.com",
},
{
  id: "728ed52a",
  userId: "1010",
  amount: 543,
  status: "success",
  fullName: "Joel Keller",
  email: "joelkeller@gmail.com",
},
{
  id: "728ed52b",
  userId: "1011",
  amount: 234,
  status: "pending",
  fullName: "Daniel Ellis",
  email: "danielellis@gmail.com",
},
{
  id: "728ed52c",
  userId: "1012",
  amount: 345,
  status: "success",
  fullName: "Gordon Kennedy",
  email: "gordonkennedy@gmail.com",
},
{
  id: "728ed52d",
  userId: "1013",
  amount: 335,
  status: "failed",
  fullName: "Emily Hoffman",
  email: "emilyhoffman@gmail.com",
},
{
  id: "728ed52e",
  userId: "1014",
  amount: 664,
  status: "pending",
  fullName: "Jeffery Garrett",
  email: "jefferygarrett@gmail.com",
},
{
  id: "728ed52f",
  userId: "1015",
  amount: 332,
  status: "success",
  fullName: "Ralph Baker",
  email: "ralphbaker@gmail.com",
},
{
  id: "728ed52g",
  userId: "1016",
  amount: 413,
  status: "failed",
  fullName: "Seth Fields",
  email: "sethfields@gmail.com",
},
{
  id: "728ed52h",
  userId: "1017",
  amount: 345,
  status: "pending",
  fullName: "Julia Webb",
  email: "juliawebb@gmail.com",
},
{
  id: "728ed52i",
  userId: "1018",
  amount: 754,
  status: "success",
  fullName: "Gary Banks",
  email: "garybanks@gmail.com",
},
{
  id: "728ed52j",
  userId: "1019",
  amount: 643,
  status: "failed",
  fullName: "Flora Chambers",
  email: "florachambers@gmail.com",
},
{
  id: "728ed52k",
  userId: "1020",
  amount: 543,
  status: "pending",
  fullName: "Steve Hanson",
  email: "stevehanson@gmail.com",
},
{
  id: "728ed52l",
  userId: "1021",
  amount: 324,
  status: "success",
  fullName: "Lola Robinson",
  email: "lolarobinson@gmail.com",
},
{
  id: "728ed52m",
  userId: "1022",
  amount: 123,
  status: "pending",
  fullName: "Ethel Waters",
  email: "ethelwaters@gmail.com",
},
{
  id: "728ed52n",
  userId: "1023",
  amount: 422,
  status: "failed",
  fullName: "Grace Edwards",
  email: "graceedwards@gmail.com",
},
{
  id: "728ed52o",
  userId: "1024",
  amount: 712,
  status: "success",
  fullName: "Sallie Wong",
  email: "salliewong@gmail.com",
},
{
  id: "728ed52p",
  userId: "1025",
  amount: 360,
  status: "success",
  fullName: "Bryan Gutierrez",
  email: "bryangutierrez@gmail.com",
},
{
  id: "728ed52q",
  userId: "1026",
  amount: 454,
  status: "pending",
  fullName: "Erik Rice",
  email: "erikrice@gmail.com",
},
{
  id: "728ed52r",
  userId: "1027",
  amount: 382,
  status: "success",
  fullName: "Jordan Atkins",
  email: "jordanatkins@gmail.com",
},
{
  id: "728ed52s",
  userId: "1028",
  amount: 328,
  status: "failed",
  fullName: "Bill Brewer",
  email: "billbrewer@gmail.com",
},
{
  id: "728ed52t",
  userId: "1029",
  amount: 250,
  status: "success",
  fullName: "Edwin Morris",
  email: "edwinmorris@gmail.com",
},
{
  id: "728ed52u",
  userId: "1030",
  amount: 658,
  status: "success",
  fullName: "Harold Becker",
  email: "haroldbecker@gmail.com",
},
{
  id: "728ed52v",
  userId: "1031",
  amount: 691,
  status: "success",
  fullName: "Hannah Rodriguez",
  email: "hannahrodriguez@gmail.com",
},
{
  id: "728ed52w",
  userId: "1032",
  amount: 969,
  status: "success",
  fullName: "Zachary Beck",
  email: "zacharybeck@gmail.com",
},
{
  id: "728ed52x",
  userId: "1033",
  amount: 617,
  status: "failed",
  fullName: "Frances Potter",
  email: "francespotter@gmail.com",
},
{
  id: "728ed52y",
  userId: "1034",
  amount: 173,
  status: "success",
  fullName: "Raymond Murray",
  email: "raymondmurray@gmail.com",
},
{
  id: "728ed52z",
  userId: "1035",
  amount: 843,
  status: "success",
  fullName: "Adam Sherman",
  email: "adamsherman@gmail.com",
},
{
  id: "728ed521f",
  userId: "1036",
  amount: 914,
  status: "pending",
  fullName: "Anne Cruz",
  email: "annecruz@gmail.com",
},
  ];
};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>
      <DataTable columns={columns} data={data}/>
    </div>
  );
};

export default PaymentsPage;